apiVersion: v1
kind: BuildConfig
labels:
    app: customerservice
metadata:
  name: customerservice-pipeline
spec:
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfile: |-
        pipeline {
            agent any
            stages {
                stage('Clone') {
                    steps {
                        echo 'test'
                        checkout([$class: 'GitSCM',
                                  branches: [[name: '*/master']],
                                  extensions: [
                                          [$class: 'RelativeTargetDirectory', relativeTargetDir: 'mavenapp']
                                  ],
                                  userRemoteConfigs: [[url: 'https://github.com/jloli/customer-service.git']]
                        ])
                    }
                }
                stage('Build Jar') {
                    steps {
                        dir('mavenapp') {
                            sh './mvnw clean package -Popenshift'
                        }
                    }
                }
                stage('Build Image') {
                    steps {
                        dir('mavenapp') {
                            sh 'oc start-build customerservice --from-dir . --follow'
                        }
                    }
                }
            }
        }
    type: JenkinsPipeline
  triggers: []